### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reset'

### ISSUE THREAD

**Issue by Freenoob7878** [FuseFairy/DiscordBot-EdgeGPT#138]
```
 ERROR    discord.ui.view Ignoring exception in view <DropdownView timeout=180 children=1> for item <Select placeholder='Choose setting' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Creative' value='Creative' description='Switch conversation style to Creative' emoji=<PartialEmoji animated=False name='🎨' id=None> default=False>, <SelectOption label='Balanced' value='Balanced' description='Switch conversation style to Balanced' emoji=<PartialEmoji animated=False name='⚖️' id=None> default=False>, <SelectOption label='Precise' value='Precise' description='Switch conversation style to Precise' emoji=<PartialEmoji animated=False name='🔎' id=None> default=False>, <SelectOption label='Reset' value='Reset' description='Reset conversation' emoji=<PartialEmoji animated=False name='🔄' id=None> default=False>]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/workspaces/workspace/cogs/event.py", line 69, in dropdown_callback
    await self.client.reset()
  File "/workspaces/workspace/src/mention_chatbot.py", line 29, in reset
    await self.chatbot.reset()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'reset'
```

i am getting this error always whenever i mention the bot or use '/copilot'

**Comment by FuseFairy** [comment]
I can't reproduce this error. Did you use any other commands before you got the error?

**Comment by Freenoob7878** [comment]
Nope.

**Comment by FuseFairy** [comment]
at src\mention_chatbot.py line8, change like this:
`self.chatbot: Chatbot = None`
