### ISSUE TITLE
HUGE error right here

### ISSUE THREAD

**Issue by astrotically** [FuseFairy/DiscordBot-EdgeGPT#142]
i followed everything and did 'python bot.py' , and got this error:

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 778, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\arief\OneDrive\Desktop\Bing\DiscordBot-EdgeGPT\cogs\edgegpt.py", line 4, in <module>
    from discord import app_commands
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\__init__.py", line 12, in <module>
    from .commands import *
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 51, in <module>
    from ..enums import AppCommandOptionType, AppCommandType, ChannelType, Locale
ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums' (C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\enums.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\arief\OneDrive\Desktop\Bing\DiscordBot-EdgeGPT\bot.py", line 36, in on_ready
    await bot.load_extension(f'cogs.{Filename[:-3]}')
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 912, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 781, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.edgegpt' raised an error: ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums' (C:\Users\arief\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\enums.py)

please help asap!

**Comment by FuseFairy** [comment]
Are you sure your discord.py version is 2.3.2 and the path is correct?
