### ISSUE TITLE
2024-05-10 18:24:44 ERROR    src.bing_chat.response -> 400, message='Can not decode content-encoding: br'

### ISSUE THREAD

**Issue by CatfishGG** [FuseFairy/DiscordBot-EdgeGPT#152]
Hey there FuseFairy! I am having an error regarding copilot.

So, The error I encountered was:
```
2024-05-10 18:24:33 INFO     cogs.event -> udpskid：'Hey there' (udpskid chatroom) [Style: balanced]
2024-05-10 18:24:35 ERROR    src.bing_chat.response -> 400, message='Can not decode content-encoding: br'
Traceback (most recent call last):
  File "D:\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\src\bing_chat\response.py", line 85, in send_message
    reply = await chatbot.ask(
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\re_edge_gpt\chat\re_edge_gpt.py", line 120, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\re_edge_gpt\chat\chathub.py", line 117, in ask_stream
    response = await upload_image_url(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\re_edge_gpt\image\upload_image.py", line 39, in upload_image_url
    return (await resp.json())["blobId"]
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1092, in json
    await self.read()
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 370, in read
    block = await self.readany()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 392, in readany
    await self._wait("readany")
  File "C:\Users\CatfishGG\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 306, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
```

It looks like this on discord.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/151020503/d8feadd4-38d7-4b22-88f0-d0f98b13ad75)

What do you think about this?

**Comment by FuseFairy** [comment]
It's still working for me, maybe try vpn?

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/1344c45a-f6b5-4fe0-ac4e-6391c6a9ddb2)

**Comment by CatfishGG** [comment]
alright wait. Let me try a VPN

**Comment by FuseFairy** [comment]
If you can, you can try running on Replit.
https://replit.com/@dd8611706/DiscordBot-EdgeGPT?v=1

**Comment by CatfishGG** [comment]
I kind of knew this was going to happen because replit's datacenters are messed up. They use 1 bare metal server for hundreds or thousands of users and because of that the traffic of the server is considered to be fraudlent.

So the new error that we have from replit is:

```
2024-05-10 13:25:15 INFO     cogs.event -> udpskid：'Hey there' (udpskid chatroom) [Style: balanced]
2024-05-10 13:25:18 ERROR    src.bing_chat.response -> CaptchaChallenge: User needs to solve CAPTCHA to continue. 
Full exception: {'type': 2, 'invocationId': '3', 'item': {'firstNewMessageIndex': None, 'defaultChatName': None, 'conversationId': '51D|BingProd|67ADA71B6CEA0CD892BA5AC76CFB9EFA5BD9F1B3ADE67794083141BF75F38ED7', 'requestId': '0f6d6c1a-c9cb-4975-8937-65fc0bd04668', 'telemetry': {'startTime': '2024-05-10T13:25:16.2207637Z'}, 'result': {'value': 'CaptchaChallenge', 'message': 'User needs to solve CAPTCHA to continue.', 'error': 'User needs to solve CAPTCHA to continue.', 'serviceVersion': '20240510.116'}}}
Traceback (most recent call last):
  File "/home/runner/DiscordBot-EdgeGPT/src/bing_chat/response.py", line 85, in send_message
    reply = await chatbot.ask(
  File "/home/runner/DiscordBot-EdgeGPT/.pythonlibs/lib/python3.10/site-packages/re_edge_gpt/chat/re_edge_gpt.py", line 120, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/runner/DiscordBot-EdgeGPT/.pythonlibs/lib/python3.10/site-packages/re_edge_gpt/chat/chathub.py", line 198, in ask_stream
    raise ResponseError(
re_edge_gpt.utils.exception.exceptions.ResponseError: CaptchaChallenge: User needs to solve CAPTCHA to continue. 
Full exception: {'type': 2, 'invocationId': '3', 'item': {'firstNewMessageIndex': None, 'defaultChatName': None, 'conversationId': '51D|BingProd|67ADA71B6CEA0CD892BA5AC76CFB9EFA5BD9F1B3ADE67794083141BF75F38ED7', 'requestId': '0f6d6c1a-c9cb-4975-8937-65fc0bd04668', 'telemetry': {'startTime': '2024-05-10T13:25:16.2207637Z'}, 'result': {'value': 'CaptchaChallenge', 'message': 'User needs to solve CAPTCHA to continue.', 'error': 'User needs to solve CAPTCHA to continue.', 'serviceVersion': '20240510.116'}}}
```

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/151020503/9362786d-2f06-4120-9e97-4a7ae2d7126b)

**Comment by CatfishGG** [comment]
also, I tried doing it on my local machine with a VPN and it still doesn't work. It just displays the 2024-05-10 19:07:47 ERROR    src.bing_chat.response -> 400, message='Can not decode content-encoding: br' error again.

**Comment by CatfishGG** [comment]
Yep, even on github codespace it displays the same error. 

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/151020503/7bff206c-f929-4970-a6a2-7ee5823f1916)

**Comment by FuseFairy** [comment]
I saw this error, you need solve captcha first.

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/92b00f1d-2127-4aa1-9c23-f4bb2d3849a6)

**Comment by CatfishGG** [comment]
FuseFairy... How will I solve the captcha if it isn't visible to me? 💀

**Comment by FuseFairy** [comment]
here's solution
https://github.com/Integration-Automation/ReEdgeGPT/issues/115

**Comment by CatfishGG** [comment]
yes, thank you for the the solution but you mentioned "copilot.com" in the reply to that issue there which isn't the URL to copilot itself. You should just replace the copilot.com to https://copilot.microsoft.com/
