### ISSUE TITLE
src.bing_chat.response -> 400 Bad Request (error code: 50035): Invalid Form Body In components.0.components.2.label: Must be 80 or fewer in length.

### ISSUE THREAD

**Issue by CatfishGG** [FuseFairy/DiscordBot-EdgeGPT#153]
The following error is what I'm getting this time,
```
Traceback (most recent call last):
  File "/workspaces/DiscordBot-EdgeGPT/src/bing_chat/response.py", line 162, in send_message
    await interaction.followup.send(response, view=ButtonView(conversation_style_str, suggest_responses, user_chatbot), embed=link_embed)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 1805, in send
    data = await adapter.execute_webhook(
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.2.label: Must be 80 or fewer in length.
```
It tells me that the response is probably too long to be displayed? I guess it must be 80 or fewer in length eh? is it possible to get a fix for this?

**Comment by FuseFairy** [comment]
ok, change src\bing_chat\button_view.py file like this:

```python
import discord
from ..log import setup_logger
from functools import partial

logger = setup_logger(__name__)

# To add suggest responses
class ButtonView(discord.ui.View):
    def __init__(self, conversation_style_str:str=None, suggest_responses:list=None, user_chatbot=None, images:list=None):
        super().__init__(timeout=120)

        if images:
            for i, image in enumerate(images, start=1):
                if i > 2:
                    self.add_item(discord.ui.Button(label=f"Link {i}", url=image, row=2))
                else:
                    self.add_item(discord.ui.Button(label=f"Link {i}", url=image, row=1))

        if conversation_style_str and suggest_responses and user_chatbot:
            # Add buttons
            for label in suggest_responses:
                label = label[:78] + "..." if len(label) > 80 else label
                button = discord.ui.Button(label=label, row=3)
                # Button event
                async def callback(interaction: discord.Interaction, button: discord.ui.Button):     
                    await interaction.response.defer(ephemeral=False, thinking=True)
                    username = str(interaction.user)
                    usermessage = button.label
                    channel = str(interaction.channel)
                    logger.info(f"\x1b[31m{username}\x1b[0m ： '{usermessage}' ({channel}) [Style: {conversation_style_str}] [button]")
                    await user_chatbot.send_message(message=usermessage, interaction=interaction)
                self.add_item(button)
                self.children[-1].callback = partial(callback, button=button)
```
