### ISSUE TITLE
Cant start bot.py

### ISSUE THREAD

**Issue by occultwave** [FuseFairy/DiscordBot-EdgeGPT#43]
leexh@DESKTOP-VK4N2SO:~/DiscordBot-EdgeGPT$ python3 bot.py
2023-03-27 21:35:57 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/leexh/DiscordBot-EdgeGPT/bot.py", line 68, in <module>
    bot.run(os.getenv("DISCORD_BOT_TOKEN"))
  File "/home/leexh/.local/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/leexh/.local/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/leexh/.local/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/home/leexh/.local/lib/python3.10/site-packages/discord/client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead

**Comment by FuseFairy** [comment]
In .env file, modify ```DISCORD_BOT_TOKEN=your_bot_token```to```DISCORD_BOT_TOKEN="your_bot_token"```

**Comment by occultwave** [comment]
> In .env file, modify ```DISCORD_BOT_TOKEN=your_bot_token```to```DISCORD_BOT_TOKEN="your_bot_token"```

Same error

**Comment by FuseFairy** [comment]
In bot.py line 68, modify ```bot.run(os.getenv("DISCORD_BOT_TOKEN"))```to```bot.run("DISCORD_BOT_TOKEN")```

**Comment by hello-navi** [comment]
You have to change .env.dev to .env.

**Comment by FuseFairy** [comment]
> You have to change .env.dev to .env.

Really for this reason, no wonder I can't reproduce this error...

**Comment by occultwave** [comment]
Everything works, thank you
