### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by braxiwni** [FuseFairy/DiscordBot-EdgeGPT#47]
When running bot.ry locally, the console gives an error.
And in the discord, the bot does not respond to commands.

[2023-04-06 19:52:36] [INFO    ] discord.client: logging in using static token
[2023-04-06 19:52:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 366a9bbd117e1689e53b565c8842990d).
←[30;1m2023-04-06 19:52:40←[0m ←[34;1mINFO    ←[0m ←[35m__main__←[0m -> GPT5#0426 is now running!
[2023-04-06 19:52:41] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Lenovo\Desktop\DiscordBot-EdgeGPT-main\cogs\edgegpt.py", line 10, in <module>
    chatbot = Chatbot("./cookies.json")
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 341, in __init__
    self.chat_hub: ChatHub = ChatHub(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 269, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Lenovo\Desktop\DiscordBot-EdgeGPT-main\bot.py", line 38, in on_ready
    await bot.load_extension(f'cogs.{Filename[:-3]}')
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 938, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.edgegpt' raised an error: KeyError: 'conversationSignature'

Screenshot: 
![image](https://user-images.githubusercontent.com/128992970/230418832-36390909-5abc-4c45-bc7d-89ace73fdfe8.png)

**Comment by FuseFairy** [comment]
https://github.com/acheong08/EdgeGPT/search?q=conversationSignature&type=issues
I'm not sure, but some people also got this error.Maybe cookies wrong?

**Comment by braxiwni** [comment]
Thank you. It was necessary to change the account in Microsoft Edge, the campaign is linked to the account and further does not allow working with Bing. Like a ban
