### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by Murat1Ahmet** [FuseFairy/DiscordBot-EdgeGPT#72]
2023-05-15 22:47:05 ERROR    src.response -> Error while sending message: Throttled: Request is throttled.
Traceback (most recent call last):
  File "/home/container/src/response.py", line 63, in send_message
    reply = await chatbot.ask(prompt=user_message, conversation_style=ConversationStyle.balanced, wss_link="wss://sydney.bing.com/sydney/ChatHub")
  File "/home/container/.local/lib/python3.10/site-packages/EdgeGPT.py", line 644, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/container/.local/lib/python3.10/site-packages/EdgeGPT.py", line 548, in ask_stream
    raise Exception(f"{response['item']['result']['value']}: {response['item']['result']['message']}")
Exception: Throttled: Request is throttled.

**Comment by FuseFairy** [comment]
Update bing cookies
