### ISSUE TITLE
Cookies File Doesn't Work

### ISSUE THREAD

**Issue by LoonaFurry** [FuseFairy/DiscordBot-EdgeGPT#98]
I Copy Cookie Information From bing.com with Chrome And I Save It Cookies File But I Try To Recopy It a Couple Of Times It's Still Doesn't Work It's Giving Me This Error I Don't Know What Should I Do But I Think The Error Related To The Cookies File Itself And The Error Message Is Here:

Traceback (most recent call last):
  File "C:\Users\^w^ Loona ^w^\Desktop\DiscordBot-EdgeGPT-main\bot.py", line 8, in <module>
    from cogs.event import set_chatbot
  File "C:\Users\^w^ Loona ^w^\Desktop\DiscordBot-EdgeGPT-main\cogs\event.py", line 26, in <module>
    cookies = json.load(file)
              ^^^^^^^^^^^^^^^
  File "C:\Users\^w^ Loona ^w^\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\^w^ Loona ^w^\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\^w^ Loona ^w^\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\^w^ Loona ^w^\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![pycharm64_4Eaw8JZZZb](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/127280966/1fe9f22e-8c60-4b99-bf24-5e1841743b03)

**Comment by FuseFairy** [comment]
pls make sure your cookies copy from here https://bing.com/

**Comment by LoonaFurry** [comment]
> pls make sure your cookies copy from here https://bing.com/

![Discord_vDtDBVGy2w](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/127280966/eeb8ca9c-6b4d-4b1e-a793-2f7677faf027)
I Fixed The Problem And Now Giving Me a New Problem I Reset The Cookies File With New Cookie And I Couple Time Restard The Bot But The Error Still Keep Exist When I Ask Something To And Bot Please Fix This Problem
Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by FuseFairy** [comment]
Here is solution https://github.com/acheong08/EdgeGPT/issues/586
